### ISSUE TITLE
SQLGetDiagRec failed: ret=-2 in Instana integration

### ISSUE THREAD

**Issue by maxatcn** [ibmdb/go_ibm_db#175]
Team,  

Can you please have a check the Instana integration issue?  Thanks.

- os Version:  ubi-minimal image 8.6-902
- cli-driver Version:  latest
- Db2 Server Version: DV 1.7.7, (Db2 11.5.2)
- go Version: go 1.18.5
<details><summary><code>go env
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/yabinma/.cache/go-build"
GOENV="/home/yabinma/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/opt/gospace/pkg/mod"
GONOPROXY="*.ibm.com"
GONOSUMDB="*.ibm.com"
GOOS="linux"
GOPATH="/opt/gospace"
GOPRIVATE="*.ibm.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/opt/gospace/src/dv-api/go.mod"
GOWORK=""
CGO_CFLAGS="-I/home/yabinma/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/home/yabinma/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3018807947=/tmp/go-build -gno-record-gcc-switches"

</code> </summary><br><pre>
</pre></details>

Steps to Reproduce:

1.    add module in go.mod,  	
        github.com/ibmdb/go_ibm_db v0.4.1
	github.com/instana/go-sensor v1.43.4
and import these two in go file,
	db2 "github.com/ibmdb/go_ibm_db"
	instana "github.com/instana/go-sensor"

2. (important) replace the sql.open with Instana one if Instana is setup to monitor,  

              ` if strings.TrimSpace(os.Getenv(utils.INSTANA_AGENT_HOST)) != "" {
		// Create a new instana.Sensor instance
		sensor := instana.NewSensor("dv-api-instana-db")

		// Instrument the driver
		instana.InstrumentSQLDriver(sensor, "go_ibm_db", &db2.Driver{})

		// Create an instance of *sql.DB to use for database queries
		db, err = instana.SQLOpen("go_ibm_db", connStringBuilder.String())
	        } else {
		db, err = sql.Open("go_ibm_db", connStringBuilder.String())
	        }`

3.  Run query as normal.

The full error stack,
```
2022/08/24 08:31:32 http: panic serving 172.30.176.12:49756: SQLGetDiagRec failed: ret=-2
goroutine 581 [running]:
net/http.(*conn).serve.func1()
	/goroot/src/net/http/server.go:1802 +0xb9
panic({0x1831ea0, 0xc000fd53a0})
	/goroot/src/runtime/panic.go:1047 +0x266
github.com/instana/go-sensor.TracingNamedHandlerFunc.func1.2()
	/gopath/pkg/mod/github.com/instana/go-sensor@v1.43.4/instrumentation_http.go:93 +0x1c5
panic({0x1831ea0, 0xc000fd53a0})
	/goroot/src/runtime/panic.go:1038 +0x215
github.com/ibmdb/go_ibm_db.NewError({0x1a86922, 0xe}, {0x17be8a0, 0x2d4d400})
	/gopath/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/error.go:58 +0x3c5
github.com/ibmdb/go_ibm_db.(*Driver).Open(0xc0002c82a0, {0xc001ddca00, 0x643})
	/gopath/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/conn.go:23 +0x2ac
github.com/instana/go-sensor.(*wrappedSQLDriver).Open(0xc001c52108, {0xc001ddca00, 0x643})
	/gopath/pkg/mod/github.com/instana/go-sensor@v1.43.4/instrumentation_sql.go:89 +0x4e
github.com/instana/go-sensor.dsnConnector.Connect(...)
	/gopath/pkg/mod/github.com/instana/go-sensor@v1.43.4/instrumentation_sql.go:493
github.com/instana/go-sensor.(*wrappedSQLConnector).Connect(0xc000244380, {0x1df2f10, 0xc00013c000})
	/gopath/pkg/mod/github.com/instana/go-sensor@v1.43.4/instrumentation_sql_go1.10.go:34 +0x37
database/sql.(*DB).conn(0xc001c22c30, {0x1df2f10, 0xc00013c000}, 0x1)
	/goroot/src/database/sql/sql.go:1364 +0x7ac
database/sql.(*DB).query(0x1f, {0x1df2f10, 0xc00013c000}, {0xc001298ae0, 0x4e}, {0x0, 0x0, 0x0}, 0x2)
	/goroot/src/database/sql/sql.go:1695 +0x5d
database/sql.(*DB).QueryContext(0xc0007f8c38, {0x1df2f10, 0xc00013c000}, {0xc001298ae0, 0x4e}, {0x0, 0x0, 0x0})
	/goroot/src/database/sql/sql.go:1674 +0xdf
database/sql.(*DB).Query(...)
	/goroot/src/database/sql/sql.go:1691
dv-api/src/apis/securities/handlers.CallGetInstanceID(0xc001cc2b00, 0x0)
	/gopath/src/dv-api/src/apis/securities/handlers/get_instanceID.go:56 +0x11d
dv-api/src/apis/securities/handlers.GetInstanceID.func1({0xc001cc2b00, 0x0})
	/gopath/src/dv-api/src/apis/securities/handlers/get_instanceID.go:28 +0xa9
```

Instana sample link with sql.Open(), https://www.ibm.com/docs/en/instana-observability/225?topic=go-collector-common-operations#how-to-instrument-a-database-connection-created-with-sqlopen

**Comment by maxatcn** [comment]
Hi Team,

I am not sure if this is the root cause. Let me show what I found here.

Inside instana.SQLOpen("go_ibm_db", conn),  it always add "_with_instana" as the suffix in the driver name. Here is the source code,
```
func SQLOpen(driverName, dataSourceName string) (*sql.DB, error) {

	if !strings.HasSuffix(driverName, "_with_instana") {
		driverName += "_with_instana"
	}

	return sql.Open(driverName, dataSourceName)
}
```
So in the sql.Open(driverName, dataSourceName), here the driverName becomes `go_ibm_db_with_instana`. 

---------------------------------------------------------------------------------------------------------------------------------------------------
When the issue happened, the error was returned from source code, 
```
func (drv *wrappedSQLDriver) Open(name string) (driver.Conn, error) {
	conn, err := drv.Driver.Open(name)
	if err != nil {
		return conn, err
	}
```

Here, the name is from t.dsn,
```
func (t dsnConnector) Connect(_ context.Context) (driver.Conn, error) {
	return t.driver.Open(t.dsn)
}
```

there are two properties in dsnConnector , dsn and driver.  Here the dsn, I am guessing it's the driver name.
```
type dsnConnector struct {
	dsn    string
	driver driver.Driver
}
```

**Comment by maxatcn** [comment]
closed since this issue is fixed in Instana side.
