### ISSUE TITLE
Panic when initDriver

### ISSUE THREAD

**Issue by tianlin** [ibmdb/go_ibm_db#199]
- os Version: CentOS Linux release 7.4.1708 (Core)
- cli-driver Version:v11.1
- Db2 Server Version:any
- go Version: go 1.18.7
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/data/parcels/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/parcels/gopath"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.7"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1192468085=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

Steps to Reproduce:

1.write a go app which import go_ibm_db
2.run this app 1000 times, and catch panic in output as follow script:
```
#!/bin/sh
cd /app/bin/
for i in {1..1000}
do
   ./app > /tmp/debug 2>&1
   cnt=`grep "panic" /tmp/debug | wc -l`
   if [[ ${cnt} -gt 0 ]]
   then
       echo "panic"
       exit 1
   fi
done

echo "ok"
```

3.open /tmp/debug to see detail 

```
runtime: bad pointer in frame github.com/ibmdb/go_ibm_db/api.SQLSetEnvAttr.func1 at 0xc0005bd770: 0x3
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw({0x20ee489?, 0x347f860?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0x7ffd80597140 sp=0x7ffd80597110 pc=0xc43bf1
runtime.adjustpointers(0x7ffd80597530?, 0x1b1f1c?, 0x2c0bcde?, {0x2fb1ce0?, 0x347f860?})
        /usr/local/go/src/runtime/stack.go:628 +0x1d0 fp=0x7ffd805971a8 sp=0x7ffd80597140 pc=0xc5d450
runtime.adjustframe(0x7ffd80597530, 0x7ffd80597620)
        /usr/local/go/src/runtime/stack.go:670 +0xc9 fp=0x7ffd80597238 sp=0x7ffd805971a8 pc=0xc5d569
runtime.gentraceback(0x0?, 0xc767e0?, 0xc0004e0000?, 0xc000560000?, 0x0, 0x0, 0x7fffffff, 0x216e358, 0xb?, 0x0)
        /usr/local/go/src/runtime/traceback.go:334 +0xc47 fp=0x7ffd80597598 sp=0x7ffd80597238 pc=0xc684c7
runtime.copystack(0xc0000021a0, 0x0?)
        /usr/local/go/src/runtime/stack.go:930 +0x2f5 fp=0x7ffd80597750 sp=0x7ffd80597598 pc=0xc5dd75
runtime.shrinkstack(0xc0000021a0)
        /usr/local/go/src/runtime/stack.go:1212 +0x126 fp=0x7ffd80597770 sp=0x7ffd80597750 pc=0xc5ec46
runtime.newstack()
        /usr/local/go/src/runtime/stack.go:1060 +0x3aa fp=0x7ffd80597928 sp=0x7ffd80597770 pc=0xc5e20a
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:547 +0x8b fp=0x7ffd80597930 sp=0x7ffd80597928 pc=0xc7470b

goroutine 1 [running, locked to thread]:
runtime.cgoCheckArg(0x1d5bf00, 0x3, 0x0?, 0x1, {0x210c0ce, 0x29})
        /usr/local/go/src/runtime/cgocall.go:445 +0x587 fp=0xc0005bd6f8 sp=0xc0005bd6f0 pc=0xc10f27
runtime.cgoCheckPointer({0x1d5bf00, 0x3}, {0x0, 0x0})
        /usr/local/go/src/runtime/cgocall.go:435 +0x156 fp=0xc0005bd740 sp=0xc0005bd6f8 pc=0xc10936
github.com/ibmdb/go_ibm_db/api.SQLSetEnvAttr.func1(0x13eeb40?, 0x0?, 0x3640bf8?, 0x55f788?)
        /root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.2/api/zapi_unix.go:114 +0x38 fp=0xc0005bd788 sp=0xc0005bd740 pc=0x13e4238
github.com/ibmdb/go_ibm_db/api.SQLSetEnvAttr(0x550001?, 0x0?, 0xc0004268d0?, 0x3640000?)
        /root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.2/api/zapi_unix.go:114 +0x19 fp=0xc0005bd7b0 sp=0xc0005bd788 pc=0x13e41b9
github.com/ibmdb/go_ibm_db.initDriver()
        /root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.2/driver.go:36 +0xb3 fp=0xc0005bd820 sp=0xc0005bd7b0 pc=0x13e6e93
github.com/ibmdb/go_ibm_db.init.0()
        /root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.2/driver.go:62 +0x3f fp=0xc0005bd860 sp=0xc0005bd820 pc=0x13e717f
runtime.doInit(0x3472700)
        /usr/local/go/src/runtime/proc.go:6222 +0x126 fp=0xc0005bd990 sp=0xc0005bd860 pc=0xc53806
runtime.doInit(0x3470960)
        /usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc0005bdac0 sp=0xc0005bd990 pc=0xc53751
runtime.doInit(0x34760e0)
        /usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc0005bdbf0 sp=0xc0005bdac0 pc=0xc53751
runtime.doInit(0x347c5c0)
        /usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc0005bdd20 sp=0xc0005bdbf0 pc=0xc53751
runtime.doInit(0x347ba80)
        /usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc0005bde50 sp=0xc0005bdd20 pc=0xc53751
runtime.doInit(0x347f420)
        /usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc0005bdf80 sp=0xc0005bde50 pc=0xc53751
runtime.main()
        /usr/local/go/src/runtime/proc.go:233 +0x1d3 fp=0xc0005bdfe0 sp=0xc0005bdf80 pc=0xc465f3
runtime.goexit()
```

**Comment by vmathur12** [comment]
@tianlin   I am not able to repro the issue in my environment. I have created a go app which will create a table, insert values in the table and display it. Ran the app for 1000 times. Attached the go app code. Could you please test with this app let me know. Or Please share your app and I will test it in my environment. Thanks.
[app.txt](https://github.com/ibmdb/go_ibm_db/files/10345027/app.txt)

**Comment by tianlin** [comment]
[db2_app.tar.gz](https://github.com/ibmdb/go_ibm_db/files/10348358/db2_app.tar.gz)
@vmathur12 , I can use the  db2_app.tar.gz to reproduce the bug, please put db2 lib to db2_app dir before run it.

**Comment by vmathur12** [comment]
@tianlin I have tested with db2_app and my app1,  still the issue is not reproduce in my environment. Attached app.tar.gz and command log file for your reference. Could you please test by reducing loop count, until it works and also check your system would have low memory. 
Thanks
[app.tar.gz](https://github.com/ibmdb/go_ibm_db/files/10357678/app.tar.gz)
[command_log.zip](https://github.com/ibmdb/go_ibm_db/files/10357685/command_log.zip)

**Comment by tianlin** [comment]
@vmathur12  I use your app.tar.gz rerun test2.sh in my env,  output is
`root@192.168.50.81:/data/app$./test2.sh
app1
1
grep: /tmp/debug: No such file or directory
app1
2
grep: /tmp/debug: No such file or directory
app1
3
grep: /tmp/debug: No such file or directory
app1
4
grep: /tmp/debug: No such file or directory
app1
5
grep: /tmp/debug: No such file or directory
app1
6
grep: /tmp/debug: No such file or directory
runtime: bad pointer in frame github.com/ibmdb/go_ibm_db/api.SQLSetEnvAttr.func1 at 0xc000175c30: 0x3
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw({0xf63d60?, 0x1b02300?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0x7fffca065d60 sp=0x7fffca065d30 pc=0x6d0091
runtime.adjustpointers(0x7fffca066150?, 0x11b1cc?, 0x164cf8e?, {0x185a108?, 0x1b02300?})
        /usr/local/go/src/runtime/stack.go:628 +0x1d0 fp=0x7fffca065dc8 sp=0x7fffca065d60 pc=0x6e82d0
runtime.adjustframe(0x7fffca066150, 0x7fffca066240)
        /usr/local/go/src/runtime/stack.go:670 +0xc9 fp=0x7fffca065e58 sp=0x7fffca065dc8 pc=0x6e83e9
runtime.gentraceback(0xc000680000?, 0x24?, 0x0?, 0x8?, 0x0, 0x0, 0x7fffffff, 0xfa6e60, 0xc000003a00?, 0x0)
        /usr/local/go/src/runtime/traceback.go:334 +0xc47 fp=0x7fffca0661b8 sp=0x7fffca065e58 pc=0x6f3347
runtime.copystack(0xc000002340, 0x6d6945?)
        /usr/local/go/src/runtime/stack.go:930 +0x2f5 fp=0x7fffca066370 sp=0x7fffca0661b8 pc=0x6e8bf5
runtime.shrinkstack(0xc000002340)
        /usr/local/go/src/runtime/stack.go:1212 +0x126 fp=0x7fffca066390 sp=0x7fffca066370 pc=0x6e9ac6
runtime.newstack()
        /usr/local/go/src/runtime/stack.go:1060 +0x3aa fp=0x7fffca066548 sp=0x7fffca066390 pc=0x6e908a
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:547 +0x8b fp=0x7fffca066550 sp=0x7fffca066548 pc=0x6fe8eb

goroutine 1 [running, locked to thread]:
runtime.cgoCheckArg(0xe7ffc0, 0x3, 0x0?, 0x1, {0xf6c021, 0x29})`

and `free` command output is:
`              total        used        free      shared  buff/cache   available
Mem:       16267168    13382292      434708      975804     2450168     1516468
Swap:             0           0           0`

**Comment by tianlin** [comment]
And I found a temp resolution is put db2 import before dm, when I do this panic will not happend.

**Comment by vmathur12** [comment]
@tianlin I am closing this issue. Let me know if you are facing issue again. Thanks
