### ISSUE TITLE
Get error "panic: runtime error: cgo argument has Go pointer to Go pointer"

### ISSUE THREAD

**Issue by asghar3** [ibmdb/go_ibm_db#40]
The I using the go_ibm_db version 0.1.1 in our golang project.

I get the following error when trying to run a sql query.

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 34 [running]:
github.com/ibmdb/go_ibm_db/api.SQLGetData.func1(0x8000900010001, 0xc0001ae7b8, 0x8, 0xc0001ae798, 0xc0001ca200)
        /go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.1.1/api/zapi_unix.go:81 +0x4c
github.com/ibmdb/go_ibm_db/api.SQLGetData(0x8000900010001, 0xc0001ae7b8, 0xc000000008, 0xc0001ae798, 0x40)
        /go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.1.1/api/zapi_unix.go:81 +0x59
github.com/ibmdb/go_ibm_db.(*BufferLen).GetData(...)
        /go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.1.1/column.go:25
github.com/ibmdb/go_ibm_db.(*BindableColumn).Value(0xc0001ae780, 0xc000010001, 0x8, 0xa3e840, 0xc0001a0960, 0x0, 0x0)
        /go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.1.1/column.go:268 +0x283
github.com/ibmdb/go_ibm_db.(*Rows).Next(0xc000214050, 0xc0001f62d0, 0x9, 0x9, 0xc000137040, 0x3)
        /go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.1.1/rows.go:99 +0xca
database/sql.(*Rows).nextLocked(0xc000222180, 0xc0001a0000)
        /usr/local/go/src/database/sql/sql.go:2680 +0xbc
database/sql.(*Rows).Next.func1()
        /usr/local/go/src/database/sql/sql.go:2658 +0x3c
database/sql.withLock(0xbf0380, 0xc0002221b0, 0xc0001370c0)
        /usr/local/go/src/database/sql/sql.go:3097 +0x63
database/sql.(*Rows).Next(0xc000222180, 0xc0001f61b0)
        /usr/local/go/src/database/sql/sql.go:2657 +0x88
```

The same SQL query runs fine on DB2WH UI.

So not sure what is going on.
Any help would be appreciated .
Thanks

**Comment by asghar3** [comment]
@akhilravuri1 Any suggestions ?

**Comment by akhilravuri1** [comment]
Hi @asghar3 

sorry, the late reply.
please provide the sql query which you are using. A sample program that reproduces the issue would be more helpful.

Thanks,
Akhil

**Comment by asghar3** [comment]
Can't provide that :S

I worked around my casting the column value to varchar and the driver was able to handle that.
